### ISSUE TITLE
Cannot use types from class libraries (csproj) in razor views

### ISSUE THREAD

**Issue by ShadowDancer** [aspnet/Razor#755]
## Title
Cannot use types from class libraries (csproj) in razor views

### Functional impact
Cannot use types from other systems in razor views (compiled code works as expected).
For example I cannot keep my cms in separate dll.

### Minimal repro steps
-create new webapplication rc2 project from template
-create new class library
-create example type in class library
-add reference to class library from rc2 project
-use type from class library

https://github.com/ShadowDancer/rc2_razor_references

### Expected result
Compiled view.

### Actual result
The type or namespace name 'ClassLibrary' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'ExampleClass' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Eilon** [comment]
@pakrym @abpiskunov @pranavkm any ideas on Razor views in a project.json project referencing types from a CSPROJ?

**Comment by juergenr** [comment]
Same problem:
- cannot reference class library
- but @using System.IO works

When I use:
   string s = File.ReadAllText(@"C:\Test\test.txt");
   I cannot view s in Debug mode!

**Comment by pranavkm** [comment]
@ShadowDancer I can't restore your project:

```
Errors in \rc2_razor_references\src\rc2test\project.json
    Unable to resolve 'ClassLibrary' for '.NETFramework,Version=v4.5.1'.
```

Are you missing something from it?

**Comment by ShadowDancer** [comment]
@pranavkm 
I can't restore it either with dotnet cli, however project is compiled successfully by VisualStudio, and all types are available in rc2test project - generally it works until you attempt to render razor view with type from ClassLibrary.

For instance in my project (I mean business project, not rc2_razor_references) I have whole Startup.cs class moved to class library and webapp is bootstrapped correctly. To demonstrate it I added new commit, so rc2_razor_references now prints "Woof!" to debug output when startup constructor is called (you need to open it in visual studio and start rc2test project), however that class is not available when razor tries to compile it into view.

I guess that It has something to do with moving away from dnx or new "preserveCompilationContext" option? Wrap projects are not used anymore, so I just referenced cspoj libraries from xproj and application is compiled (but not razor).

**Comment by patrikwlund** [comment]
I don't know if this has any effect on this, but project.fragment.lock.json puts the location of ClassLibrary.dll here:
bin/Debug/ClassLibrary.dll

instead of here (where it's actually located):
bin/Debug/net451/win7-x64/ClassLibrary.dll

**Comment by ShadowDancer** [comment]
@patrikwlund 
Looks like that paths in *.lock.json files are relative to project or package root, so
bin/Debug/ClassLibrary.dll
is relative to csproj directory
/ClassLibrary
directory, and dll file is there.

**Comment by abpiskunov** [comment]
@patrikwlund  could you please specify what was your xproj and csproj project types and their target frameworks? i need to know that to see what is going on with paths specified in fragment.lock file.

**Comment by abpiskunov** [comment]
Also, here is related issue https://github.com/aspnet/Mvc/issues/4686 . See my reply there.

**Comment by patrikwlund** [comment]
@abpiskunov I cloned ShadowDancer's solution, so:
Rc2 web application + csproj class library
Both for net451

**Comment by ShadowDancer** [comment]
@abpiskunov 
Correct me If I am wrong, but if dll is missing (for instance if I manually delete ClassLibrary.dll from my output folder) exception is thrown when I attempt to execute code from that deleted assembly.

In provided example I can execute that code, so dll is loaded. Somehow Razor compiler cannot use that assembly though.

**Comment by abpiskunov** [comment]
About dll path, with your projects and target frameworks, it seems that fragment json has correct path to ClassLibrary.dll located under csproj path. The path bin/Debug/net451/win7-x64/ClassLibrary.dll that you specified is where it was copied under web app's. 

If that is true, it means that for your case of net451 - dlls are copied (the active issue in RC2 was about netstandard target framework). and yes, problem is that dll indeed is not used/found correctly by compiler at runtime.

**Comment by abpiskunov** [comment]
Please confirm that dll is copied under web app's bin folder. Btw, you can refernce code in VS and intellisense works for you, because in VS references are resolved via project references not just dlls as it happens at runtime, thats why it works in VS.

**Comment by ShadowDancer** [comment]
Yes it is, as pointed out by partrikwlund:
bin/Debug/net451/win7-x64/ClassLibrary.dll

Here is entire bin folder if you want to take look (rc2test is AspNetCore webapp and ClassLibrary.dll is csproj):
http://pastebin.com/3z0vrAfC

>Btw, you can refernce code in VS and intellisense works for you, because in VS references are resolved via project references not just dlls as it happens at runtime, thats why it works in VS

To make it clear - it works as runtime for code compiled from .cs files. I can use class from dll in AspNetCore executable - it compiles and executes without problem.
It doesn't work for code generated by razor at runtime from .cshtml with types from referenced .csproj assembly. Compiler throws when attempting to compile.

**Comment by pranavkm** [comment]
@ShadowDancer - Razor compilation in Mvc uses the deps file that is produced by the compiler when you set `preserveCompilationContext` to determine what assemblies to use for runtime compilation. It seems that the deps file is missing bits of useful information for Razor compilation to discover csproj based class library references \ binaries. For RC2, you should be able to work around this by explicitly adding references to Razor compilation using `RazorViewEngineOptions.CompilationCallback`. See https://github.com/aspnet/Mvc/issues/4087#issuecomment-191899644

**Comment by patrikwlund** [comment]
@pranavkm @ShadowDancer I can confirm that setting `RazorViewEngineOptions.CompilationCallback` does the job as a workaround. The razor view compiles successully.

```
var myAssemblies = AppDomain.CurrentDomain.GetAssemblies().Select(x => MetadataReference.CreateFromFile(x.Location)).ToList();

services.Configure((RazorViewEngineOptions options) =>
{
    var previous = options.CompilationCallback;
    options.CompilationCallback = (context) =>
    {
        previous?.Invoke(context);

        context.Compilation = context.Compilation.AddReferences(myAssemblies);
    };
});
```

**Comment by Eilon** [comment]
BTW I set up a quick mtg for Monday to discuss this.

**Comment by Eilon** [comment]
Assigning to @pakrym because he is fixing this issue in .NET CLI.

**Comment by Eilon** [comment]
BTW there's a workaround that might work for you. See https://github.com/aspnet/Mvc/issues/4686#issuecomment-220779628.

**Comment by bhalkett** [comment]
Can someone can tell me if I'm experiencing another facet of the same issue identified or something different. 

First, I got the sample code that @ShadowDancer linked in the first post.  I verified that the code fails when the Index.cshtml razor file is dynamically compiled at runtime.

Second, I got the code working by adding the following workaround code to the startup.cs file:
<div class="highlight highlight-source-cs">
<pre>
services.AddMvc()
        .AddRazorOptions(options =&gt;
        {
            <span class="pl-k">var</span> previous = options.CompilationCallback;
            options.CompilationCallback = context =&gt;
            {
                previous?.Invoke(context);

                context.Compilation = context.Compilation.AddReferences(MetadataReference.CreateFromFile(<span class="pl-k">typeof</span>(MyClass).Assembly.Location));
            };
        })
</pre>
</div>

Finally, I broke the code again by adding the following property to the Dog class:
<div class="highlight highlight-source-cs">
<pre>
        public string Name { get; set; }
</pre>
</div>

And then the contents of the Index.cshtml with the following:
<div class="highlight highlight-source-cs">
<pre>
@model ClassLibrary.Dog

@Html.DisplayNameFor(model => model.Name)
@Html.DisplayFor(model => model.Name)
</pre>
</div>

Here's the error message I get:
![image](https://cloud.githubusercontent.com/assets/6025169/15490416/88ebd04a-211c-11e6-983c-2fd1573fde58.png)

**Comment by ShadowDancer** [comment]
Workaround works for me too. In case you have any dynamic assemblies you want to skip them:
```
 AppDomain.CurrentDomain.GetAssemblies()
                    .Where(x => !x.IsDynamic)
                    .Select(x => MetadataReference.CreateFromFile(x.Location))
                    .ToList();
```

**Comment by bhalkett** [comment]
I created a new issue [here](http://github.com/aspnet/Razor/issues/763).

**Comment by pakrym** [comment]
@ShadowDancer should be fixed in `Microsoft.AspNetCore.*` `1.0.0-rc3-21130` packages and `1.0.0-preview2-002886` of CLI. Can please verify fix on your side too?

**Comment by bhalkett** [comment]
@pakrym It now works for me without the workaround with <code>1.0.0-rc3-21130</code> packages and <code>1.0.0-preview2-002909</code> of CLI.

Although it does compile and run correctly, I am getting the following error in VS:
![capture](https://cloud.githubusercontent.com/assets/6025169/15691139/0842ee3a-273c-11e6-9b6e-9accaca70765.JPG)

My Dog class looks like this:
<pre>
<code>
namespace ClassLibrary
{
    public class Dog
    {
        public string Name { get; set; }

        public string Bark()
        {
            return "Woof!";
        }
    }
}
</code>
</pre>

And my Index view looks like this:
<pre>
<code>
@model ClassLibrary.Dog
@using ClassLibrary

&ltbr /&gt
&ltlabel asp-for="Name"&gt&lt/label&gt
&ltinput asp-for="Name" /&gt
&ltbr /&gt
@(new Dog().Bark())
</code>
</pre>

I look forward to seeing the results from @ShadowDancer.

**Comment by bhalkett** [comment]
My problem described above has been resolved.  I hadn't set "Microsoft.AspNetCore.Razor.Tools" correctly under dependencies in the project.json file.  So all is good!

**Comment by ShadowDancer** [comment]
@pakrym 
Yes it works with 1.0.0-rc3-21130.

**Comment by ShadowDancer** [comment]
@pakrym 
I discovered side effect of this fix (on RTM). If I move Startup class to class library, no types in WebApplication can be used in razor view. To show that I updated sample project:
https://github.com/ShadowDancer/rc2_razor_references

TestModel used by partial view is located in WebApplication project. Startup is located in assembly. Result - compilation error. If I move startup to WebApplication now my class is discovered correctly.

I guess that I should be using areas here, but I thought that You should know.

**Comment by Alchemy86** [comment]
Hi,

Is this still an issue. I used the work around previously but now I've come back to it after some time and all I get is: 

Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

Any idea why this might be? If I remote the work around my login page complains of not knowing the type which is again one in an external project ref in the project.

**Comment by nloding** [comment]
@pakrym These workarounds do not work for me. I'm using .NET Core 1.1.0 on macOS, and the workarounds above don't work. I've triple checked everything in the thread, but I consistently get `One or more compilation references are missing. Possible causes include a missing 'preserveCompilationContext' property under 'buildOptions' in the application's project.json.`

Anyone have any additional thoughts?

**Comment by nloding** [comment]
Turns out I had an error during `dotnet build` that wasn't being revealed when I debugged in VS Code. Once that was resolved, it works just fine. Ignore my last comment!
