### ISSUE TITLE
With 2.1.300-preview2-008322, Razor precompilation isn't back-compatible with 2.0.0 applications

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Razor#2168]
Repro:

* Create this trivial project: https://gist.github.com/SteveSandersonMS/0d25e89db93b8092577c3e10d428b533
* Run `dotnet publish -c Release`

Expected: Publish succeeds
Actual: With the preview 2 SDK, it fails with the following error:

```
EXEC : warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options. [C:\Users\username\Desktop\tmpaspnet\tmpaspnet.csproj]
EXEC(1,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\username\Desktop\tmpaspnet\tmpaspnet.csproj]
EXEC(1,54): error CS0518: Predefined type 'System.String' is not defined or imported [C:\Users\username\Desktop\tmpaspnet\tmpaspnet.csproj]
C:\Users\username\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(60,5): error MSB3073: The command ""C:\Users\username\.dotnet\x64\dotnet.exe" exec --runtimeconfig "C:\Users\username\Desktop\tmpaspnet\bin\Release\netcoreapp2.0\tmpaspnet.runtimeconfig.json" --depsfile "C:\Users\username\Desktop\tmpaspnet\bin\Release\netcoreapp2.0\tmpaspnet.deps.json" "C:\Users\username\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1. [C:\Users\username\Desktop\tmpaspnet\tmpaspnet.csproj]
```

Note that the same steps work fine with the 2.1.0-preview1 final SDK (and of course with 2.0.x).

**Comment by rynowak** [comment]
@pranavkm have you seen anything like this before?

The error message looks like a restore failure, or possibly reference assemblies not being passed through.

**Comment by pranavkm** [comment]
Same root cause as https://github.com/aspnet/MvcPrecompilation/issues/162. We don't produce `PreserveCompilationContext` any more on apps without cshtml files. Perhaps we should leave the behavior of `PreserveCompilationContext` unchanged if we infer an older target:

`<PreserveCompilationContext Condition="'$(ResolvedRazorCompileToolSet)'=='MvcPrecompilation'">true</PreserveCompilationContext>`

**Comment by rynowak** [comment]
I think we absolutely have to do this if it's breaking stuff.

**Comment by pranavkm** [comment]
Thanks for reporting this @SteveSandersonMS
